version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: bitbox-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitbox
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bitbox-api:
    depends_on:
      - postgres
    image: bixbox-back:1.0.0
    container_name: bixbox-api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://user:password@localhost:5433/notation
      # Tokens
      JWT_SECRET: secret
      JWT_EXPIRES_IN: 24
      JWT_PASSWORD_RESET_EXPIRES_IN: 10
      # SMTP
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: port
      SMTP_USERNAME: username
      SMTP_PASSWORD: Thisispassword
      # API Admin
      ADMIN_EMAIL: contact@gmail.com
      DEFAULT_ADMIN_PASSWORD: admin
      ADMIN_PASSWORD: Thisisadminpassword
      # React app URL
      WEB_URL: http://localhost:3000
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "localhost:5433", "--", "sh", "-c", "diesel migration run && main"]

  bitbox-front:
    image: bixbox-front:1.0.0
    container_name: bixbox-front
    network_mode: "bridge"
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api

volumes:
  postgres_data: